[profile.default]
src = "src"
out = "out"
libs = ["lib"]
# solc = "0.8.20"

remappings = [
    "@openzeppelin/=lib/openzeppelin-contracts/",
    "@openzeppelin-06/=lib/openzeppelin-contracts-06/",
    "forge-std/=lib/forge-std/src/"
]

# eth_rpc_url = 'https://rpc.ankr.com/eth_goerli'
eth_rpc_url = 'https://rpc.ankr.com/eth_sepolia'
etherscan_api_key = '${ETHERSCAN_KEY}'


